import React from 'react'
import PostAuthor from './components/PostAuthor'
import { Link } from 'react-router-dom'
import Thumbnail from './images/1.png'

function PostDetail() {
  return (
    <>
    <section className='container post-detail'>
      <div className="post-detail-container">
        <div className="post-detail-header">
          <PostAuthor/>
          <div className="post-detail-buttons">
            <Link to={`/posts/werf/edit`} className='btn'>Edit</Link>
            <Link to={`/posts/werf/delete`} className='btn red'>Delete</Link>
          </div>
        </div>
        <h1>This is the post title!</h1>
        <div className="post-detail-thumbnail">
          <img src={Thumbnail} alt="" />
        </div>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum tempore libero officia dolore perferendis. Veritatis quaerat rerum eveniet dignissimos dolor laboriosam, repellendus exercitationem accusantium explicabo quod, consequuntur voluptates iusto reprehenderit. Ipsam, hic ad. Numquam iure placeat provident facere inventore ullam sunt voluptates nam labore aspernatur, necessitatibus sint? Doloremque, dolorum libero amet ea officiis cupiditate totam fugiat quod animi quae minima architecto odit soluta. Laboriosam esse voluptatibus enim quaerat officia nesciunt inventore sunt eveniet, odio deserunt consequuntur voluptate quos ex, porro necessitatibus. At voluptates praesentium, provident qui sint facilis distinctio similique dolorem quod labore? Laboriosam similique deserunt animi! Perferendis accusamus et quis soluta? Reprehenderit, exercitationem. Culpa assumenda nisi autem laudantium tempora veniam quibusdam minus? Quidem, corrupti eaque iste suscipit cum aut nemo sapiente numquam quia amet corporis ipsam quod accusantium quasi tempore doloremque ex incidunt sunt, sint odit vitae similique distinctio! Facere eveniet voluptate corrupti possimus dolor iste ratione. Nostrum nesciunt earum itaque numquam, obcaecati suscipit tempora sed cum consectetur, fuga rerum deserunt enim aspernatur fugiat deleniti fugit. Quibusdam maxime facilis vel doloribus ullam quaerat eveniet, neque optio voluptas illum. Ullam iusto repellat distinctio ipsum eveniet esse voluptate, et id culpa fuga quidem ratione earum exercitationem! Atque iste inventore excepturi molestias doloribus facilis aliquid distinctio itaque quisquam cupiditate! Suscipit possimus autem, dicta excepturi perspiciatis repellat nemo atque, debitis non, a dolor tenetur ipsam omnis? Modi, aut consectetur recusandae eligendi rerum nostrum officiis beatae vero ipsa non repellendus labore inventore sapiente aliquid ratione doloribus sequi rem harum temporibus vitae laudantium quae dolores! Quae quidem aliquid similique magni odio sequi, quasi nulla commodi deserunt, rem ipsam ducimus odit amet itaque vel laudantium alias placeat non, fugiat sed accusantium distinctio praesentium temporibus inventore. Adipisci praesentium illum ratione similique consequatur voluptatem blanditiis, placeat dolorem distinctio dicta sequi unde. Odit, quibusdam consequatur nisi vitae voluptas reiciendis.
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum tempore libero officia dolore perferendis. Veritatis quaerat rerum eveniet dignissimos dolor laboriosam, repellendus exercitationem accusantium explicabo quod, consequuntur voluptates iusto reprehenderit. Ipsam, hic ad. Numquam iure placeat provident facere inventore ullam sunt voluptates nam labore aspernatur, necessitatibus sint? Doloremque, dolorum libero amet ea officiis cupiditate totam fugiat quod animi quae minima architecto odit soluta. Laboriosam esse voluptatibus enim quaerat officia nesciunt inventore sunt eveniet, odio deserunt consequuntur voluptate quos ex, porro necessitatibus. At voluptates praesentium, provident qui sint facilis distinctio similique dolorem quod labore? Laboriosam similique deserunt animi! Perferendis accusamus et quis soluta? Reprehenderit, exercitationem. Culpa assumenda nisi autem laudantium tempora veniam quibusdam minus? Quidem, corrupti eaque iste suscipit cum aut nemo sapiente numquam quia amet corporis ipsam quod accusantium quasi tempore doloremque ex incidunt sunt, sint odit vitae similique distinctio! Facere eveniet voluptate corrupti possimus dolor iste ratione. Nostrum nesciunt earum itaque numquam, obcaecati suscipit tempora sed cum consectetur, fuga rerum deserunt enim aspernatur fugiat deleniti fugit. Quibusdam maxime facilis vel doloribus ullam quaerat eveniet, neque optio voluptas illum. Ullam iusto repellat distinctio ipsum eveniet esse voluptate, et id culpa fuga quidem ratione earum exercitationem! Atque iste inventore excepturi molestias doloribus facilis aliquid distinctio itaque quisquam cupiditate! Suscipit possimus autem, dicta excepturi perspiciatis repellat nemo atque, debitis non, a dolor tenetur ipsam omnis? Modi, aut consectetur recusandae eligendi rerum nostrum officiis beatae vero ipsa non repellendus labore inventore sapiente aliquid ratione doloribus sequi rem harum temporibus vitae laudantium quae dolores! Quae quidem aliquid similique magni odio sequi, quasi nulla commodi deserunt, rem ipsam ducimus odit amet itaque vel laudantium alias placeat non, fugiat sed accusantium distinctio praesentium temporibus inventore. Adipisci praesentium illum ratione similique consequatur voluptatem blanditiis, placeat dolorem distinctio dicta sequi unde. Odit, quibusdam consequatur nisi vitae voluptas reiciendis.
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum tempore libero officia dolore perferendis. Veritatis quaerat rerum eveniet dignissimos dolor laboriosam, repellendus exercitationem accusantium explicabo quod, consequuntur voluptates iusto reprehenderit. Ipsam, hic ad. Numquam iure placeat provident facere inventore ullam sunt voluptates nam labore aspernatur, necessitatibus sint? Doloremque, dolorum libero amet ea officiis cupiditate totam fugiat quod animi quae minima architecto odit soluta. Laboriosam esse voluptatibus enim quaerat officia nesciunt inventore sunt eveniet, odio deserunt consequuntur voluptate quos ex, porro necessitatibus. At voluptates praesentium, provident qui sint facilis distinctio similique dolorem quod labore? Laboriosam similique deserunt animi! Perferendis accusamus et quis soluta? Reprehenderit, exercitationem. Culpa assumenda nisi autem laudantium tempora veniam quibusdam minus? Quidem, corrupti eaque iste suscipit cum aut nemo sapiente numquam quia amet corporis ipsam quod accusantium quasi tempore doloremque ex incidunt sunt, sint odit vitae similique distinctio! Facere eveniet voluptate corrupti possimus dolor iste ratione. Nostrum nesciunt earum itaque numquam, obcaecati suscipit tempora sed cum consectetur, fuga rerum deserunt enim aspernatur fugiat deleniti fugit. Quibusdam maxime facilis vel doloribus ullam quaerat eveniet, neque optio voluptas illum. Ullam iusto repellat distinctio ipsum eveniet esse voluptate, et id culpa fuga quidem ratione earum exercitationem! Atque iste inventore excepturi molestias doloribus facilis aliquid distinctio itaque quisquam cupiditate! Suscipit possimus autem, dicta excepturi perspiciatis repellat nemo atque, debitis non, a dolor tenetur ipsam omnis? Modi, aut consectetur recusandae eligendi rerum nostrum officiis beatae vero ipsa non repellendus labore inventore sapiente aliquid ratione doloribus sequi rem harum temporibus vitae laudantium quae dolores! Quae quidem aliquid similique magni odio sequi, quasi nulla commodi deserunt, rem ipsam ducimus odit amet itaque vel laudantium alias placeat non, fugiat sed accusantium distinctio praesentium temporibus inventore. Adipisci praesentium illum ratione similique consequatur voluptatem blanditiis, placeat dolorem distinctio dicta sequi unde. Odit, quibusdam consequatur nisi vitae voluptas reiciendis.
        </p>
      </div>
    </section>
    </>
  )
}

export default PostDetail